#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT.btor2" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/caliptra-wdt
upstream=$fixture/upstream/wdt.sv
wrapper=$fixture/wrapper-word-input.sv
expected_upstream=a9127035f25736258059b435a3d3aeba91cc93283ffcdd34bd80e2716ae84045
expected_wrapper=c3a0e6cc09a7835e5d0d05db27a6d6b2dfb526c05c5ed04bdcf8bcf13244ff30
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

[[ $(sha256_file "$upstream") == "$expected_upstream" ]] || {
  echo "pinned Caliptra source digest mismatch" >&2
  exit 2
}
[[ $(sha256_file "$wrapper") == "$expected_wrapper" ]] || {
  echo "pinned Caliptra word-input wrapper digest mismatch" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-caliptra-word-input.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
cp "$upstream" "$wrapper" "$scratch/"
raw=$scratch/model.raw.btor2
(
  cd "$scratch"
  "$yosys" -Q -q -p "
    read_verilog -formal -sv wdt.sv wrapper-word-input.sv;
    hierarchy -check -top caliptra_wdt_word_input;
    proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
    clean -purge; write_btor $raw
  "
)
case $(sed -n '1p' "$raw") in
  '; BTOR description generated by Yosys '*) ;;
  *) echo "unexpected Yosys BTOR header" >&2; exit 2 ;;
esac

canonical=$scratch/model.btor2
{
  printf '; BTOR description generated by pinned Yosys commit %s for module caliptra_wdt_word_input.\n' \
    "$expected_yosys"
  sed -n '2,$p' "$raw"
} >"$canonical"

if ! (set -C; cat "$canonical" >"$output") 2>/dev/null; then
  echo "refusing to overwrite $output" >&2
  exit 2
fi
printf 'caliptra_wdt_word_input_btor2=CREATED source_sha256=%s wrapper_sha256=%s yosys_revision=%s output=%s\n' \
  "$expected_upstream" "$expected_wrapper" "$expected_yosys" "$output"
