#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 5 ]]; then
  echo "usage: $0 YOSYS CORE_BEFORE.btor2 CORE_AFTER.btor2 CHANNEL_BEFORE.btor2 CHANNEL_AFTER.btor2" >&2
  exit 2
fi

yosys=$1
core_before_output=$2
core_after_output=$3
channel_before_output=$4
channel_after_output=$5
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-pwm-crosstalk-impact
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}
for output in "$core_before_output" "$core_after_output" "$channel_before_output" "$channel_after_output"; do
  [[ ! -e "$output" && ! -L "$output" ]] || {
    echo "refusing to overwrite $output" >&2
    exit 2
  }
done

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}
check_digest() {
  [[ $(sha256_file "$2") == "$1" ]] || {
    echo "pinned fixture digest mismatch: $2" >&2
    exit 2
  }
}

check_digest 519596e56c11ef7023356ddfdb75ec97c16fcc61b4f2983bd52a7eb17e0b73c7 "$fixture/core-before-specialized.sv"
check_digest b122a48144d587f185610d36e811edd5ec0b9f7608d5b8e806eb80b5be46bddb "$fixture/core-after-specialized.sv"
check_digest bfd38560962bcc16d70e7a91e6a3252eec478807cde38a30979c03accc69a05b "$fixture/channel-before-specialized.sv"
check_digest 4683a1a74086ceba2b6dc27bdee057ed32937489f74fc0bbdbffb4fa62777f78 "$fixture/channel-after-specialized.sv"
check_digest b5650d6c28465875f3e5c21d93c85b0cd228b4f233047baf85f8ade29ea421c2 "$fixture/upstream-86db289.patch"

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-pwm-impact.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
cp "$fixture"/{core-before-specialized.sv,core-after-specialized.sv,channel-before-specialized.sv,channel-after-specialized.sv} "$scratch/"

build_raw() {
  local source=$1
  local top=$2
  local raw=$3
  (
    cd "$scratch"
    "$yosys" -Q -q -p "
      read_verilog -formal -sv $source;
      hierarchy -check -top $top;
      proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
      clean -purge; write_btor $raw
    "
  )
}

canonicalize_core() {
  local raw=$1
  local output=$2
  awk -v revision="$3" -v yosys_revision="$expected_yosys" '
    /^; BTOR description generated by Yosys / {
      printf "; BTOR description generated by pinned Yosys %s for OpenTitan PWM core %s.\n", yosys_revision, revision
      next
    }
    { sub(/ ; [^;]*-specialized[.]sv:.*/, "") }
    $2 == "output" {
      if ($4 == "raw_pwm_o") raw_pwm = $3
      if ($4 == "phase_four_o") phase_four = $3
      if ($4 == "phase_two_o") phase_two = $3
      if ($4 == "clear_o") clear = $3
    }
    /^; end of yosys output$/ {
      if (!raw_pwm || !phase_four || !phase_two || !clear) exit 2
      printf "1000 redor 1 %s canonical_raw_pwm\n", raw_pwm
      printf "1001 redor 1 %s canonical_phase_four\n", phase_four
      printf "1002 redor 1 %s canonical_phase_two\n", phase_two
      printf "1003 redor 1 %s canonical_clear\n", clear
      print "1100 output 1000 canonical_raw_pwm"
      print "1101 output 1001 canonical_phase_four"
      print "1102 output 1002 canonical_phase_two"
      print "1103 output 1003 canonical_clear"
    }
    { print }
  ' "$raw" >"$scratch/canonical-core.btor2"
  (set -C; cp "$scratch/canonical-core.btor2" "$output") 2>/dev/null || {
    echo "refusing to overwrite $output" >&2
    exit 2
  }
}

canonicalize_channel() {
  local raw=$1
  local output=$2
  awk -v revision="$3" -v yosys_revision="$expected_yosys" '
    /^; BTOR description generated by Yosys / {
      printf "; BTOR description generated by pinned Yosys %s for OpenTitan PWM channel %s.\n", yosys_revision, revision
      next
    }
    { sub(/ ; [^;]*-specialized[.]sv:.*/, "") }
    $2 == "output" {
      if ($4 == "core_only_bad_o") core_bad = $3
      if ($4 == "channel_only_bad_o") channel_bad = $3
      if ($4 == "joint_bad_o") joint_bad = $3
      if ($4 == "reset_safe_bad_o") reset_bad = $3
      if ($4 == "impossible_bad_o") impossible_bad = $3
    }
    /^; end of yosys output$/ {
      if (!core_bad || !channel_bad || !joint_bad || !reset_bad || !impossible_bad) exit 2
      printf "1000 redor 1 %s canonical_core_only_bad\n", core_bad
      printf "1001 redor 1 %s canonical_channel_only_bad\n", channel_bad
      printf "1002 redor 1 %s canonical_joint_bad\n", joint_bad
      printf "1003 redor 1 %s canonical_reset_safe_bad\n", reset_bad
      printf "1004 redor 1 %s canonical_impossible_bad\n", impossible_bad
      print "1100 output 1000 canonical_core_only_bad"
      print "1101 output 1001 canonical_channel_only_bad"
      print "1102 output 1002 canonical_joint_bad"
      print "1103 output 1003 canonical_reset_safe_bad"
      print "1104 output 1004 canonical_impossible_bad"
    }
    { print }
  ' "$raw" >"$scratch/canonical-channel.btor2"
  (set -C; cp "$scratch/canonical-channel.btor2" "$output") 2>/dev/null || {
    echo "refusing to overwrite $output" >&2
    exit 2
  }
}

build_raw core-before-specialized.sv opentitan_pwm_core_impact "$scratch/core-before.raw.btor2"
canonicalize_core "$scratch/core-before.raw.btor2" "$core_before_output" before
build_raw core-after-specialized.sv opentitan_pwm_core_impact "$scratch/core-after.raw.btor2"
canonicalize_core "$scratch/core-after.raw.btor2" "$core_after_output" after
build_raw channel-before-specialized.sv opentitan_pwm_channel_impact "$scratch/channel-before.raw.btor2"
canonicalize_channel "$scratch/channel-before.raw.btor2" "$channel_before_output" before
build_raw channel-after-specialized.sv opentitan_pwm_channel_impact "$scratch/channel-after.raw.btor2"
canonicalize_channel "$scratch/channel-after.raw.btor2" "$channel_after_output" after

echo "opentitan_pwm_crosstalk_impact_v1=GENERATED atoms=2 combinations=4 queries=5"
