#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT_DIR" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/roalogic-plic-gateway
cohort=$fixture/revision-cohort
expected_current=bab7c8c1fa31b760f41bedb840288f40b61b460b82f0620f1128f622ca711a7b
expected_initial=a7f01fdf58c3bab4597b26a2c54784add31a2fa897a61bc7e59af872de284933
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-plic-revision-aiger.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
mkdir "$scratch/out"

build_revision() {
  label=$1
  revision=$2
  expected_source=$3
  directory=$scratch/$label
  mkdir "$directory"
  cp "$fixture/upstream/plic_gateway.sv" "$directory/plic_gateway.sv"
  cp "$cohort/oracle-wrapper.sv" "$directory/oracle-wrapper.sv"
  if [[ $label == old ]]; then
    patch -R -s "$directory/plic_gateway.sv" "$cohort/e3483ddb-to-2e8dc667.patch"
  fi
  [[ $(sha256_file "$directory/plic_gateway.sv") == "$expected_source" ]] || {
    echo "reconstructed PLIC source digest mismatch: $label" >&2
    exit 2
  }
  for property in safe unsafe; do
    if [[ $property == safe ]]; then
      parameter=0
    else
      parameter=1
    fi
    (
      cd "$directory"
      "$yosys" -Q -q -p "
        read_verilog -formal -sv plic_gateway.sv oracle-wrapper.sv;
        chparam -set CHECK_REPEATED_PENDING $parameter roalogic_plic_gateway_revision_oracle;
        hierarchy -check -top roalogic_plic_gateway_revision_oracle;
        proc; flatten; async2sync; opt;
        techmap; opt; dffunmap; simplemap; dffunmap; aigmap; clean;
        setundef -zero -init;
        write_aiger -ascii -zinit -symbols $scratch/out/$label-$property.raw.aag
      "
    )
    sed "s/^Generated by Yosys .*$/Generated by pinned Yosys $expected_yosys/" \
      "$scratch/out/$label-$property.raw.aag" >"$scratch/out/$label-$property.aag"
    rm "$scratch/out/$label-$property.raw.aag"
    header=$(sed -n '1p' "$scratch/out/$label-$property.aag")
    bads=$(printf '%s\n' "$header" | awk '{print ($1 == "aag" && NF >= 7) ? $7 : 0}')
    [[ $bads -eq 1 ]] || { echo "AIGER property count mismatch" >&2; exit 1; }
  done
  printf '%s %s\n' "$revision" "$expected_source" >>"$scratch/out/sources.txt"
}

build_revision old e3483ddb06687799e2df81144659c3ec5eff3278 "$expected_initial"
build_revision new 2e8dc667f6ab69befaebdc30de7a9a53e925dbcc "$expected_current"
cmp "$scratch/out/old-safe.aag" "$scratch/out/new-safe.aag"
cmp "$scratch/out/old-unsafe.aag" "$scratch/out/new-unsafe.aag"
(
  cd "$scratch/out"
  for file in *.aag sources.txt; do
    printf '%s  %s\n' "$(sha256_file "$file")" "$file"
  done
) >"$scratch/out/SHA256SUMS"
mv "$scratch/out" "$output"
echo "roalogic_plic_revision_aiger_v1=GENERATED revisions=2 properties=2 semantic_models_identical=true output=$output"
