#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT.btor2" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/roalogic-plic-gateway
upstream=$fixture/upstream/plic_gateway.sv
wrapper=$fixture/wrapper-constrained-predicate-set.sv
expected_upstream=bab7c8c1fa31b760f41bedb840288f40b61b460b82f0620f1128f622ca711a7b
expected_license=919790362f3dfbb5f921e0b31e0104e97d8ded413ea3f73238ab2d22ae1c628f
expected_wrapper=053546d5286f41c9ce0a0fdd30feb25e6b4466f436a2d4c47424afe99a412ba0
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

[[ $(sha256_file "$upstream") == "$expected_upstream" ]] || {
  echo "pinned PLIC source digest mismatch" >&2
  exit 2
}
[[ $(sha256_file "$fixture/UPSTREAM_LICENSE.txt") == "$expected_license" ]] || {
  echo "pinned PLIC licence digest mismatch" >&2
  exit 2
}
[[ $(sha256_file "$wrapper") == "$expected_wrapper" ]] || {
  echo "pinned constrained PLIC wrapper digest mismatch" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-plic-constrained-btor2.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
raw=$scratch/model.raw.btor2
cp "$upstream" "$wrapper" "$scratch/"
(
  cd "$scratch"
  "$yosys" -Q -q -p "
    read_verilog -formal -sv plic_gateway.sv wrapper-constrained-predicate-set.sv;
    hierarchy -check -top roalogic_plic_gateway_constrained_predicate_set;
    proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
    clean -purge; write_btor $raw
  "
)
case $(sed -n '1p' "$raw") in
  '; BTOR description generated by Yosys '*) ;;
  *) echo "unexpected Yosys BTOR header" >&2; exit 2 ;;
esac

canonical=$scratch/model.btor2
{
  printf '; BTOR description generated by pinned Yosys commit %s for module roalogic_plic_gateway_constrained_predicate_set.\n' \
    "$expected_yosys"
  sed -n '2,$p' "$raw"
} >"$canonical"

if ! (set -C; cat "$canonical" >"$output") 2>/dev/null; then
  echo "refusing to overwrite $output" >&2
  exit 2
fi
printf 'roalogic_plic_gateway_constrained_btor2=CREATED source_sha256=%s yosys_revision=%s output=%s\n' \
  "$expected_upstream" "$expected_yosys" "$output"
