#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 YOSYS ENVIRONMENT.btor2 BEFORE.btor2 AFTER.btor2" >&2
  exit 2
fi

yosys=$1
environment_output=$2
before_output=$3
after_output=$4
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-prim-count-revision
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
for output in "$environment_output" "$before_output" "$after_output"; do
  [[ ! -e "$output" && ! -L "$output" ]] || {
    echo "refusing to overwrite $output" >&2
    exit 2
  }
done

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

check_digest() {
  local expected=$1
  local path=$2
  [[ $(sha256_file "$path") == "$expected" ]] || {
    echo "pinned fixture digest mismatch: $path" >&2
    exit 2
  }
}

check_digest 09111e515699f50816f7571bb8bb62b86f55bb70bdce34600a2008b16d71a061 \
  "$fixture/prim-count-before-specialized.sv"
check_digest 5ce24a22bfe53ed6d1c99104e568d1bd8071114502b81ba357c350e73dbfda87 \
  "$fixture/prim-count-after-specialized.sv"
check_digest 20afbc6a0f8c2f1389a879d0abc93475805d6c49f24ffe2098b28d07724d039a \
  "$fixture/component-wrapper.sv"
check_digest c26ab60f0be79646af3812559793ecef303ad7f569d34f42c5465c69c950a2d1 \
  "$fixture/environment-wrapper.sv"
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-prim-count.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
cp "$fixture/prim-count-before-specialized.sv" "$scratch/"
cp "$fixture/prim-count-after-specialized.sv" "$scratch/"
cp "$fixture/component-wrapper.sv" "$scratch/"
cp "$fixture/environment-wrapper.sv" "$scratch/"

build_component() {
  local revision=$1
  local source=$2
  local root=$3
  local output=$4
  local raw=$scratch/$revision.raw.btor2
  (
    cd "$scratch"
    "$yosys" -Q -q -p "
      read_verilog -formal -sv -DPRIM_COUNT_MODULE=opentitan_prim_count_$revision \
        $source component-wrapper.sv;
      hierarchy -check -top opentitan_prim_count_revision_component;
      proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
      clean -purge; write_btor $raw
    "
  )
  {
    printf '; BTOR description generated by pinned Yosys commit %s for OpenTitan prim_count %s.\n' \
      "$expected_yosys" "$revision"
    sed -n '2,$p' "$raw" | awk -v root="$root" -v revision="$revision" '
    /^; end of yosys output$/ {
      print "100 redor 3 " root " count_is_full_stable"
      print "101 output 100 count_is_full_stable"
    }
    { print }
    '
  } >"$scratch/$revision.btor2"
  if ! (set -C; cp "$scratch/$revision.btor2" "$output") 2>/dev/null; then
    echo "refusing to overwrite $output" >&2
    exit 2
  fi
}

environment_raw=$scratch/environment.raw.btor2
(
  cd "$scratch"
  "$yosys" -Q -q -p "
    read_verilog -formal -sv environment-wrapper.sv;
    hierarchy -check -top opentitan_prim_count_revision_environment;
    proc; opt; setundef -zero -init; clean -purge; write_btor $environment_raw
  "
)
{
  printf '; BTOR description generated by pinned Yosys commit %s for the OpenTitan prim_count environment.\n' \
    "$expected_yosys"
  sed -n '2,$p' "$environment_raw"
} >"$scratch/environment.btor2"
if ! (set -C; cp "$scratch/environment.btor2" "$environment_output") 2>/dev/null; then
  echo "refusing to overwrite $environment_output" >&2
  exit 2
fi

build_component before prim-count-before-specialized.sv 41 "$before_output"
build_component after prim-count-after-specialized.sv 30 "$after_output"

printf 'opentitan_prim_count_revision_v1=CREATED upstream_before=%s upstream_after=%s yosys_revision=%s\n' \
  34157c7afb84a7be7b1b1250d673f9fa8a3c18ce \
  369cffc85db0e6d5a667676a6f89987b94210e70 "$expected_yosys"
