#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 YOSYS ENVIRONMENT.btor2 BEFORE.btor2 AFTER.btor2" >&2
  exit 2
fi

yosys=$1
environment_output=$2
before_output=$3
after_output=$4
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-prim-count-revision
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
for output in "$environment_output" "$before_output" "$after_output"; do
  [[ ! -e "$output" && ! -L "$output" ]] || { echo "refusing to overwrite $output" >&2; exit 2; }
done

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}
check_digest() {
  [[ $(sha256_file "$2") == "$1" ]] || { echo "pinned fixture digest mismatch: $2" >&2; exit 2; }
}
check_digest 09111e515699f50816f7571bb8bb62b86f55bb70bdce34600a2008b16d71a061 "$fixture/prim-count-before-specialized.sv"
check_digest 5ce24a22bfe53ed6d1c99104e568d1bd8071114502b81ba357c350e73dbfda87 "$fixture/prim-count-after-specialized.sv"
check_digest 81fb8494722ee5b753c2c61544a11ff086f16820f234dc6d5c00e8a305a3d605 "$fixture/query-component-wrapper.sv"
check_digest c26ab60f0be79646af3812559793ecef303ad7f569d34f42c5465c69c950a2d1 "$fixture/environment-wrapper.sv"
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || { echo "Yosys revision mismatch" >&2; exit 2; }

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-prim-query.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
cp "$fixture"/{prim-count-before-specialized.sv,prim-count-after-specialized.sv,query-component-wrapper.sv,environment-wrapper.sv} "$scratch/"

build_component() {
  local revision=$1
  local source=$2
  local roots=$3
  local output=$4
  local raw=$scratch/$revision.raw.btor2
  (
    cd "$scratch"
    "$yosys" -Q -q -p "
      read_verilog -formal -sv -DPRIM_COUNT_MODULE=opentitan_prim_count_$revision $source query-component-wrapper.sv;
      hierarchy -check -top opentitan_prim_count_query_component;
      proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
      clean -purge; write_btor $raw
    "
  )
  {
    printf '; BTOR description generated by pinned Yosys commit %s for OpenTitan prim_count %s query service.\n' "$expected_yosys" "$revision"
    sed -n '2,$p' "$raw" | awk -v roots="$roots" '
      BEGIN { split(roots, r, ",") }
      /^; end of yosys output$/ {
        for (i = 1; i <= 8; i++) {
          printf "%d redor 3 %s query_property_%d_stable\n", 999 + i, r[i], i - 1
        }
        for (i = 1; i <= 8; i++) {
          printf "%d output %d query_property_%d_stable\n", 1099 + i, 999 + i, i - 1
        }
      }
      { print }
    '
  } >"$scratch/$revision.btor2"
  (set -C; cp "$scratch/$revision.btor2" "$output") 2>/dev/null || { echo "refusing to overwrite $output" >&2; exit 2; }
}

(
  cd "$scratch"
  "$yosys" -Q -q -p "read_verilog -formal -sv environment-wrapper.sv; hierarchy -check -top opentitan_prim_count_revision_environment; proc; opt; setundef -zero -init; clean -purge; write_btor $scratch/environment.raw.btor2"
)
{
  printf '; BTOR description generated by pinned Yosys commit %s for the OpenTitan prim_count query environment.\n' "$expected_yosys"
  sed -n '2,$p' "$scratch/environment.raw.btor2"
} >"$scratch/environment.btor2"
(set -C; cp "$scratch/environment.btor2" "$environment_output") 2>/dev/null || { echo "refusing to overwrite $environment_output" >&2; exit 2; }

build_component before prim-count-before-specialized.sv '54,51,49,47,45,14,15,16' "$before_output"
build_component after prim-count-after-specialized.sv '45,42,39,36,34,15,16,17' "$after_output"
printf 'opentitan_prim_count_query_service_v1=CREATED properties=8 yosys_revision=%s\n' "$expected_yosys"
