#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT_DIR" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-prim-count-revision
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

[[ $(sha256_file "$fixture/prim-count-before-specialized.sv") == \
  09111e515699f50816f7571bb8bb62b86f55bb70bdce34600a2008b16d71a061 ]]
[[ $(sha256_file "$fixture/prim-count-after-specialized.sv") == \
  5ce24a22bfe53ed6d1c99104e568d1bd8071114502b81ba357c350e73dbfda87 ]]
[[ $(sha256_file "$fixture/oracle-wrapper.sv") == \
  22858ac5ca7bd506b3a3853a3fe1dce74cde1999e5a78a1c9b50e7d8b0057e4f ]]

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-prim-aiger.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
mkdir "$scratch/out"
cp "$fixture/prim-count-before-specialized.sv" "$scratch/"
cp "$fixture/prim-count-after-specialized.sv" "$scratch/"
cp "$fixture/oracle-wrapper.sv" "$scratch/"

for revision in before after; do
  (
    cd "$scratch"
    "$yosys" -Q -q -p "
      read_verilog -formal -sv -DPRIM_COUNT_MODULE=opentitan_prim_count_$revision \
        prim-count-$revision-specialized.sv oracle-wrapper.sv;
      hierarchy -check -top opentitan_prim_count_revision_oracle;
      proc; flatten; async2sync; opt;
      techmap; opt; dffunmap; simplemap; dffunmap; aigmap; clean;
      setundef -zero -init;
      write_aiger -ascii -zinit -symbols out/$revision.raw.aag
    "
  )
  sed "s/^Generated by Yosys .*$/Generated by pinned Yosys $expected_yosys/" \
    "$scratch/out/$revision.raw.aag" >"$scratch/out/$revision.aag"
  header=$(sed -n '1p' "$scratch/out/$revision.aag")
  bads=$(printf '%s\n' "$header" | awk '{print ($1 == "aag" && NF >= 7) ? $7 : 0}')
  [[ $bads -eq 1 ]] || { echo "AIGER property count mismatch" >&2; exit 1; }
done

if cmp -s "$scratch/out/before.aag" "$scratch/out/after.aag"; then
  echo "semantic revision unexpectedly produced identical AIGER models" >&2
  exit 1
fi
rm "$scratch/out/before.raw.aag" "$scratch/out/after.raw.aag"
printf '%s %s\n' \
  34157c7afb84a7be7b1b1250d673f9fa8a3c18ce \
  a864392c228b1d4f4a6b4dc3baae21db3fb3afa2869d440a72623cfc9a061a45 \
  >"$scratch/out/sources.txt"
printf '%s %s\n' \
  369cffc85db0e6d5a667676a6f89987b94210e70 \
  f7256b26530637658956353adf2fa99bc4fdfd25ffcc44474f62138d9cd7d78b \
  >>"$scratch/out/sources.txt"
(
  cd "$scratch/out"
  for file in before.aag after.aag sources.txt; do
    printf '%s  %s\n' "$(sha256_file "$file")" "$file"
  done
) >"$scratch/out/SHA256SUMS"
mv "$scratch/out" "$output"
echo "opentitan_prim_count_revision_aiger_v1=GENERATED semantic_models_identical=false output=$output"
