#!/bin/sh
set -eu

if [ "$#" -ne 2 ]; then
  echo "usage: $0 YOSYS_BINARY OUTPUT_DIRECTORY" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd -P)
fixture=$repo/corpus/rtl/caliptra-wdt
top=caliptra_wdt_bounded_aiger
upstream=$fixture/upstream/wdt.sv
wrapper=$fixture/wrapper-bounded-aiger.sv
expected_upstream=a9127035f25736258059b435a3d3aeba91cc93283ffcdd34bd80e2716ae84045
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

test -x "$yosys"
if [ -e "$output" ] || [ -L "$output" ]; then
  echo "refusing to overwrite $output" >&2
  exit 2
fi

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "sha256sum or shasum is required" >&2
    exit 2
  fi
}

test "$(sha256_file "$upstream")" = "$expected_upstream" || {
  echo "pinned Caliptra source digest mismatch" >&2
  exit 2
}
case $("$yosys" -V) in
  *"git sha1 $expected_yosys,"*) ;;
  *) echo "Yosys revision mismatch" >&2; exit 2 ;;
esac

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-caliptra-aiger.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
mkdir "$scratch/out"
cp "$upstream" "$wrapper" "$scratch/"

build_model() {
  horizon=$1
  mask=$2
  label=$3
  model=$scratch/out/h${horizon}-${label}.aag
  (
    cd "$scratch"
    "$yosys" -Q -q -p "
    read_verilog -sv wdt.sv wrapper-bounded-aiger.sv;
    chparam -set Horizon $horizon -set PropertyMask $mask $top;
    hierarchy -check -top $top;
    proc; flatten; async2sync; opt;
    techmap; opt; dffunmap; simplemap; dffunmap; aigmap; clean;
    setundef -zero -init;
    write_aiger -ascii -zinit -symbols \
      -ywmap out/h${horizon}-${label}.ywmap \
      out/h${horizon}-${label}.aag
  "
  )
  ywmap=$scratch/out/h${horizon}-${label}.ywmap
  sed "s/^Generated by Yosys .*$/Generated by pinned Yosys $expected_yosys/" \
    "$model" >"${model}.canonical"
  sed "s/^  \"gennerator\": \"Yosys .*\",$/  \"gennerator\": \"Pinned Yosys $expected_yosys\",/" \
    "$ywmap" >"${ywmap}.canonical"
  mv "${model}.canonical" "$model"
  mv "${ywmap}.canonical" "$ywmap"
  test "$(grep -c "^Generated by pinned Yosys $expected_yosys$" "$model")" -eq 1
  test "$(grep -c "^  \"gennerator\": \"Pinned Yosys $expected_yosys\",$" "$ywmap")" -eq 1
  header=$(sed -n '1p' "$model")
  bads=$(printf '%s\n' "$header" | awk '{print ($1 == "aag" && NF >= 7) ? $7 : 0}')
  expected=$(printf '%s' "$mask" | awk '{n=$1; c=0; while(n){c+=n%2; n=int(n/2)}; print c}')
  test "$bads" -eq "$expected" || {
    echo "AIGER bad-property count mismatch: h${horizon}-${label}" >&2
    exit 1
  }
}

for horizon in 2 3 5; do
  build_model "$horizon" 1 t1
  build_model "$horizon" 2 t2
  build_model "$horizon" 4 fatal
done
build_model 2 7 safe-set
build_model 3 6 safe-set

(
  cd "$scratch/out"
  for file in *.aag *.ywmap; do
    shasum -a 256 "$file"
  done
) >"$scratch/out/SHA256SUMS"
mv "$scratch/out" "$output"
echo "caliptra_wdt_aiger=GENERATED models=11 output=$output"
