#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 YOSYS REVISION OUTPUT.btor2" >&2
  exit 2
fi

yosys=$1
revision=$2
output=$3
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/roalogic-plic-gateway
current=$fixture/upstream/plic_gateway.sv
cohort=$fixture/revision-cohort
wrapper=$cohort/component-wrapper.sv
expected_current=bab7c8c1fa31b760f41bedb840288f40b61b460b82f0620f1128f622ca711a7b
expected_initial=a7f01fdf58c3bab4597b26a2c54784add31a2fa897a61bc7e59af872de284933
expected_license=919790362f3dfbb5f921e0b31e0104e97d8ded413ea3f73238ab2d22ae1c628f
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

[[ $(sha256_file "$current") == "$expected_current" ]] || {
  echo "pinned current PLIC source digest mismatch" >&2
  exit 2
}
[[ $(sha256_file "$fixture/UPSTREAM_LICENSE.txt") == "$expected_license" ]] || {
  echo "pinned PLIC licence digest mismatch" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-plic-revision.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
source_file=$scratch/plic_gateway.sv
cp "$current" "$source_file"
case "$revision" in
  2e8dc667f6ab69befaebdc30de7a9a53e925dbcc)
    expected_source=$expected_current
    ;;
  e3483ddb06687799e2df81144659c3ec5eff3278)
    patch -R -s "$source_file" "$cohort/e3483ddb-to-2e8dc667.patch"
    expected_source=$expected_initial
    ;;
  *)
    echo "unsupported PLIC revision: $revision" >&2
    exit 2
    ;;
esac
[[ $(sha256_file "$source_file") == "$expected_source" ]] || {
  echo "reconstructed PLIC revision digest mismatch" >&2
  exit 2
}
cp "$wrapper" "$scratch/"
raw=$scratch/model.raw.btor2
(
  cd "$scratch"
  "$yosys" -Q -q -p "
    read_verilog -formal -sv plic_gateway.sv component-wrapper.sv;
    hierarchy -check -top roalogic_plic_gateway_revision_component;
    proc; opt; flatten; opt; async2sync; dffunmap; setundef -zero -init;
    clean -purge; write_btor $raw
  "
)
case $(sed -n '1p' "$raw") in
  '; BTOR description generated by Yosys '*) ;;
  *) echo "unexpected Yosys BTOR header" >&2; exit 2 ;;
esac

canonical=$scratch/model.btor2
{
  printf '; BTOR description generated by pinned Yosys commit %s from Roa Logic PLIC revision %s.\n' \
    "$expected_yosys" "$revision"
  sed -n '2,$p' "$raw"
} >"$canonical"
if ! (set -C; cat "$canonical" >"$output") 2>/dev/null; then
  echo "refusing to overwrite $output" >&2
  exit 2
fi
printf 'roalogic_plic_revision_component=CREATED source_revision=%s source_sha256=%s yosys_revision=%s output=%s\n' \
  "$revision" "$expected_source" "$expected_yosys" "$output"
