#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT_DIR" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-pwm-crosstalk-impact
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "refusing to overwrite $output" >&2
  exit 2
}
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}
check_digest() {
  [[ $(sha256_file "$2") == "$1" ]] || {
    echo "pinned fixture digest mismatch: $2" >&2
    exit 2
  }
}

check_digest 519596e56c11ef7023356ddfdb75ec97c16fcc61b4f2983bd52a7eb17e0b73c7 "$fixture/core-before-specialized.sv"
check_digest b122a48144d587f185610d36e811edd5ec0b9f7608d5b8e806eb80b5be46bddb "$fixture/core-after-specialized.sv"
check_digest bfd38560962bcc16d70e7a91e6a3252eec478807cde38a30979c03accc69a05b "$fixture/channel-before-specialized.sv"
check_digest 4683a1a74086ceba2b6dc27bdee057ed32937489f74fc0bbdbffb4fa62777f78 "$fixture/channel-after-specialized.sv"
check_digest c60ef5963e1ae4b2824a3a546cd5ebc5e86da3bc01258085b36890e602910b87 "$fixture/maintained-oracle-wrapper.sv"
check_digest b5650d6c28465875f3e5c21d93c85b0cd228b4f233047baf85f8ade29ea421c2 "$fixture/upstream-86db289.patch"

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-pwm-aiger.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
mkdir "$scratch/out"
cp "$fixture"/{core-before-specialized.sv,core-after-specialized.sv,channel-before-specialized.sv,channel-after-specialized.sv,maintained-oracle-wrapper.sv} "$scratch/"

for mask in 0 1 2 3; do
  if (( mask & 1 )); then core=after; else core=before; fi
  if (( mask & 2 )); then channel=after; else channel=before; fi
  for property in 0 1 2 3 4; do
    raw=$scratch/out/mask${mask}-query${property}.raw.aag
    (
      cd "$scratch"
      "$yosys" -Q -q -p "
        read_verilog -formal -sv core-$core-specialized.sv channel-$channel-specialized.sv maintained-oracle-wrapper.sv;
        hierarchy -check -top opentitan_pwm_crosstalk_impact_oracle -chparam PROPERTY_INDEX $property;
        proc; flatten; async2sync; opt; techmap; opt; dffunmap; simplemap; dffunmap;
        aigmap; clean; setundef -zero -init;
        write_aiger -ascii -zinit -symbols $raw
      "
    )
    sed "s/^Generated by Yosys .*$/Generated by pinned Yosys $expected_yosys/" \
      "$raw" >"$scratch/out/mask${mask}-query${property}.aag"
    [[ $(awk 'NR == 1 { print ($1 == "aag" && NF >= 7) ? $7 : 0 }' "$scratch/out/mask${mask}-query${property}.aag") -eq 1 ]]
    rm "$raw"
  done
done

(
  cd "$scratch/out"
  for file in *.aag; do
    printf '%s  %s\n' "$(sha256_file "$file")" "$file"
  done
) >"$scratch/out/SHA256SUMS"
mv "$scratch/out" "$output"
echo "opentitan_pwm_crosstalk_impact_aiger_v1=GENERATED combinations=4 queries=5 models=20 output=$output"
