#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 YOSYS OUTPUT_DIRECTORY" >&2
  exit 2
fi

yosys=$1
output=$2
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-aon-timer
upstream=$fixture/upstream/aon_timer_core.sv
expected_upstream=226ed77228b49c3d9231027410b5572ae7812bb0ed76dc6679c18ef028895d2b
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159

[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ -d "$output" && ! -L "$output" ]] || { echo "output must be a non-symlink directory" >&2; exit 2; }
for name in watchdog-small.btor2 watchdog-scale.btor2; do
  [[ ! -e "$output/$name" && ! -L "$output/$name" ]] || {
    echo "refusing to overwrite $output/$name" >&2
    exit 2
  }
done

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "sha256sum or shasum is required" >&2
    exit 2
  fi
}

[[ $(sha256_file "$upstream") == "$expected_upstream" ]] || {
  echo "pinned OpenTitan source digest mismatch" >&2
  exit 2
}
[[ $("$yosys" -V) == *"git sha1 $expected_yosys,"* ]] || {
  echo "Yosys revision mismatch" >&2
  exit 2
}

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-aon.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
sed -f "$fixture/normalize-yosys.sed" "$upstream" >"$scratch/aon_timer_core.sv"
cp "$fixture/compat/aon_timer_reg_pkg.sv" "$scratch/"
cp "$fixture/compat/lc_ctrl_pkg.sv" "$scratch/"
cp "$fixture/wrapper.sv" "$scratch/"

build() {
  local threshold=$1 destination=$2
  local raw=$destination.raw
  (
    cd "$scratch"
    "$yosys" -Q -p "
      read_verilog -sv lc_ctrl_pkg.sv aon_timer_reg_pkg.sv aon_timer_core.sv wrapper.sv;
      chparam -set BiteThreshold $threshold opentitan_aon_watchdog_bounded;
      hierarchy -check -top opentitan_aon_watchdog_bounded;
      proc; opt; flatten; opt; async2sync; dffunmap; clean -purge;
      write_btor $raw
    " >/dev/null
  )
  case $(sed -n '1p' "$scratch/$raw") in
    '; BTOR description generated by Yosys '*) ;;
    *)
      echo "unexpected Yosys BTOR header" >&2
      exit 2
      ;;
  esac
  {
    printf '; BTOR description generated by pinned Yosys commit %s for module opentitan_aon_watchdog_bounded.\n' \
      "$expected_yosys"
    sed -n '2,$p' "$scratch/$raw"
  } >"$scratch/$destination"
}

output=$(cd "$output" && pwd -P)
build 9 watchdog-small.btor2
build 4000000000 watchdog-scale.btor2
for name in watchdog-small.btor2 watchdog-scale.btor2; do
  if ! (set -C; cat "$scratch/$name" >"$output/$name") 2>/dev/null; then
    echo "refusing to overwrite $output/$name" >&2
    exit 2
  fi
done
printf 'opentitan_aon_watchdog_btor2=CREATED source_sha256=%s yosys_revision=%s\n' \
  "$expected_upstream" "$expected_yosys"
