#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
  echo "usage: $0 YOSYS OUTPUT_DIR [PROPERTY_INDEXES]" >&2
  exit 2
fi

yosys=$1
output=$2
property_indexes=${3:-0,1,2,3,4,5,6,7}
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
fixture=$repo/corpus/rtl/opentitan-prim-count-revision
expected_yosys=b8e7da6f40ae8f552c116bf6c359b07c6533e159
[[ -x "$yosys" ]] || { echo "Yosys must be executable" >&2; exit 2; }
[[ ! -e "$output" && ! -L "$output" ]] || { echo "refusing to overwrite $output" >&2; exit 2; }
[[ $($yosys -V) == *"git sha1 $expected_yosys,"* ]] || { echo "Yosys revision mismatch" >&2; exit 2; }

IFS=, read -r -a properties <<<"$property_indexes"
[[ ${#properties[@]} -ge 1 && ${#properties[@]} -le 8 ]] || {
  echo "PROPERTY_INDEXES must contain between one and eight indexes" >&2
  exit 2
}
previous=-1
for property in "${properties[@]}"; do
  case "$property" in
    [0-7]) ;;
    *) echo "PROPERTY_INDEXES must be strictly increasing indexes from 0 to 7" >&2; exit 2 ;;
  esac
  (( property > previous )) || {
    echo "PROPERTY_INDEXES must be strictly increasing indexes from 0 to 7" >&2
    exit 2
  }
  previous=$property
done

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}
check_digest() {
  [[ $(sha256_file "$2") == "$1" ]] || { echo "pinned fixture digest mismatch: $2" >&2; exit 2; }
}
check_digest 09111e515699f50816f7571bb8bb62b86f55bb70bdce34600a2008b16d71a061 "$fixture/prim-count-before-specialized.sv"
check_digest 5ce24a22bfe53ed6d1c99104e568d1bd8071114502b81ba357c350e73dbfda87 "$fixture/prim-count-after-specialized.sv"
check_digest bd0f3ceba09deb60e9d77c2ecab635473694c804486fefc10f9c513419c42401 "$fixture/query-oracle-wrapper.sv"

scratch=$(mktemp -d "${TMPDIR:-/tmp}/gcc-opentitan-query-aiger.XXXXXXXX")
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
mkdir "$scratch/out"
cp "$fixture"/{prim-count-before-specialized.sv,prim-count-after-specialized.sv,query-oracle-wrapper.sv} "$scratch/"
for revision in before after; do
  for property in "${properties[@]}"; do
    (
      cd "$scratch"
      "$yosys" -Q -q -p "
        read_verilog -formal -sv -DPRIM_COUNT_MODULE=opentitan_prim_count_$revision prim-count-$revision-specialized.sv query-oracle-wrapper.sv;
        hierarchy -check -top opentitan_prim_count_query_oracle -chparam PROPERTY_INDEX $property;
        proc; flatten; async2sync; opt; techmap; opt; dffunmap; simplemap; dffunmap; aigmap; clean;
        setundef -zero -init; write_aiger -ascii -zinit -symbols out/$revision-$property.raw.aag
      "
    )
    sed "s/^Generated by Yosys .*$/Generated by pinned Yosys $expected_yosys/" "$scratch/out/$revision-$property.raw.aag" >"$scratch/out/$revision-$property.aag"
    [[ $(awk 'NR == 1 { print ($1 == "aag" && NF >= 7) ? $7 : 0 }' "$scratch/out/$revision-$property.aag") -eq 1 ]]
    rm "$scratch/out/$revision-$property.raw.aag"
  done
done
(
  cd "$scratch/out"
  for file in *.aag; do printf '%s  %s\n' "$(sha256_file "$file")" "$file"; done
) >"$scratch/out/SHA256SUMS"
mv "$scratch/out" "$output"
echo "opentitan_prim_count_query_aiger_v1=GENERATED revisions=2 distinct_properties=${#properties[@]} models=$((${#properties[@]} * 2)) output=$output"
