#!/usr/bin/env python3
"""Remove only a validated host-specific Yosys SMT-LIB generator banner."""

import argparse
import re
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("banner_output", type=Path)
    parser.add_argument("yosys_revision")
    parser.add_argument("module")
    args = parser.parse_args()

    if not args.input.is_file() or args.input.is_symlink():
        raise SystemExit("SMT-LIB input must be an ordinary file")
    if args.output.exists() or args.output.is_symlink():
        raise SystemExit("refusing to overwrite portable SMT-LIB output")
    if args.banner_output.exists() or args.banner_output.is_symlink():
        raise SystemExit("refusing to overwrite generator-banner output")
    if re.fullmatch(r"[0-9a-f]{40}", args.yosys_revision) is None:
        raise SystemExit("invalid Yosys revision")
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", args.module) is None:
        raise SystemExit("invalid SMT-LIB module")

    lines = args.input.read_bytes().splitlines(keepends=True)
    if len(lines) < 2:
        raise SystemExit("SMT-LIB input is incomplete")

    prefix = b"; SMT-LIBv2 description generated by Yosys "
    revision = f"(git sha1 {args.yosys_revision}, Release, ".encode()
    if (
        not lines[0].startswith(prefix)
        or revision not in lines[0]
        or not lines[0].endswith(b")\n")
    ):
        raise SystemExit("unexpected SMT-LIB generator banner")

    expected_module = f"; yosys-smt2-module {args.module}\n".encode()
    if lines[1] != expected_module:
        raise SystemExit("unexpected SMT-LIB module declaration")

    args.banner_output.write_bytes(lines[0])
    args.output.write_bytes(b"".join(lines[1:]))


if __name__ == "__main__":
    main()
