#!/usr/bin/env python3
"""Hostile checks for the narrowly scoped Yosys SMT-LIB portability rule."""

import hashlib
import subprocess
import tempfile
from pathlib import Path

REVISION = "b8e7da6f40ae8f552c116bf6c359b07c6533e159"
MODULE = "opentitan_pwm_firmware_trace_harness"
BODY = f"; yosys-smt2-module {MODULE}\n(declare-sort |state| 0)\n".encode()


def run_case(root: Path, name: str, model: bytes) -> tuple[int, bytes]:
    source = root / f"{name}.smt2"
    output = root / f"{name}.portable.smt2"
    banner = root / f"{name}.banner.txt"
    source.write_bytes(model)
    process = subprocess.run(
        [
            "python3",
            "scripts/canonicalize-yosys-smt2-portable-v2.py",
            str(source),
            str(output),
            str(banner),
            REVISION,
            MODULE,
        ],
        check=False,
        capture_output=True,
    )
    return process.returncode, output.read_bytes() if output.exists() else b""


with tempfile.TemporaryDirectory() as temporary:
    root = Path(temporary)
    darwin = (
        f"; SMT-LIBv2 description generated by Yosys 0.67+post "
        f"(git sha1 {REVISION}, Release, AppleClang clang++ 21)\n"
    ).encode()
    linux = (
        f"; SMT-LIBv2 description generated by Yosys 0.67+ "
        f"(git sha1 {REVISION}, Release, GNU /usr/bin/c++ 13)\n"
    ).encode()

    darwin_status, darwin_body = run_case(root, "darwin", darwin + BODY)
    linux_status, linux_body = run_case(root, "linux", linux + BODY)
    assert darwin_status == 0
    assert linux_status == 0
    assert darwin_body == linux_body == BODY

    wrong_revision = linux.replace(REVISION.encode(), b"0" * 40)
    assert run_case(root, "wrong-revision", wrong_revision + BODY)[0] != 0
    assert run_case(root, "missing-banner", BODY)[0] != 0
    wrong_module = BODY.replace(MODULE.encode(), b"wrong_top")
    assert run_case(root, "wrong-module", linux + wrong_module)[0] != 0

    changed_body = BODY + b"(assert false)\n"
    changed_status, changed_output = run_case(
        root, "changed-body", linux + changed_body
    )
    assert changed_status == 0
    assert hashlib.sha256(changed_output).digest() != hashlib.sha256(BODY).digest()

print("yosys_smt2_portability_v2_hostile=PASS controls=4")
